on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install renv and restore project dependencies
      - name: Install renv and restore dependencies
        run: |
          install.packages("renv")
          renv::restore()

      # Step 4: Set up Quarto CLI
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 5: Render and publish the Quarto project
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
